新好友见面语: 旅行者你好呀，这里是{nickname}，对我说“help”查看帮助吧~
新群见面语: 旅行者们大家好呀，这里是{nickname}，对我说“help”查看帮助吧~
群新人欢迎语:
  默认: 欢迎新旅行者~{at_user}{img:.\resources\LittlePaimon\emoticons\派蒙-交给我吧.png}
  123456789: 针对群123456789的欢迎语
群欢迎语禁用列表:
  - 123456789
  - 987654321